name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Rename the artifact
      run: copy build\libs\storage-api-1.0-SNAPSHOT.jar storage-api-${{ github.sha }}.jar
    - name: Save the artifact
      uses: actions/upload-artifact@main
      with:
        name: storage-api
        path: storage-api-${{ github.sha }}.jar
